[project]
name = "yummversetext2image"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.10.1",
    "diffusers>=0.35.1",
    "fastapi>=0.116.1",
    "invisible-watermark>=0.2.0",
    "pydantic>=2.11.9",
    "safetensors>=0.6.2",
    "torch>=2.8.0",
    "transformers>=4.56.1",
    "uvicorn[standard]>=0.35.0",
]
